from pygame.locals import *

# Dims

BLOCK_DIM = 40
N_XPOSITIONS = 30
N_YPOSITIONS = 20
SCREEN_WIDTH = BLOCK_DIM * (N_XPOSITIONS + 1)
SCREEN_HEIGHT = BLOCK_DIM * (N_YPOSITIONS + 1)


# Constants for game timer
GAME_EVENT = USEREVENT + 1
GAME_PERIOD = 200

# Colors
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)